name: This is default runner for github actions
on: push
jobs:
  mycicd:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code from SCM
        uses: actions/checkout@v4
        
      - name: Display the message
        run: echo "Hello from Narasimha reddy"
